In [13]:
import pandas as pd
import numpy as np
# import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix,multilabel_confusion_matrix


In [11]:
!pip install seaborn

Defaulting to user installation because normal site-packages is not writeable


In [15]:
df = pd.read_csv('Iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [16]:
df.Species.value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: Species, dtype: int64

In [17]:
from sklearn.datasets import load_iris

In [18]:
ds = load_iris()

In [19]:
ds.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [20]:
ds.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [21]:
iris_df = pd.DataFrame(ds.data, columns=ds.feature_names)
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [22]:
iris_df = pd.DataFrame(ds.data, columns=ds.feature_names)
iris_df['Target'] = ds.target
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     Target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [23]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [24]:
df['Species']

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [25]:
df['Species'].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: Species, dtype: int64

In [26]:
le = LabelEncoder()
le.fit_transform(df.Species)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [27]:
df.Species.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [28]:
lx = df.Species.unique().tolist()
lx.sort()
lx

['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']

In [29]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     Target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [30]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   Target             150 non-null    int32  
dtypes: float64(4), int32(1)
memory usage: 5.4 KB


In [31]:
iris_df.Target.value_counts()

0    50
1    50
2    50
Name: Target, dtype: int64

In [32]:
iris_df.Target.value_counts()/len(iris_df.Target) * 100

0    33.333333
1    33.333333
2    33.333333
Name: Target, dtype: float64

In [33]:
sns.countplot(iris_df.Target)

NameError: name 'sns' is not defined

# Model Training

In [34]:
x = iris_df.drop(['Target'],axis=1)
x

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [35]:
y = iris_df['Target']
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Target, Length: 150, dtype: int32

In [36]:
x_train,x_test,y_train, y_test = train_test_split(x,y,test_size=0.25,random_state=19,stratify=y)
x_train.shape,x_test.shape

((112, 4), (38, 4))

In [37]:
y_test.shape,y_train.shape

((38,), (112,))

In [38]:
model = LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

# Model Evaluation

In [39]:
## on testing data


y_pred = model.predict(x_test)
y_pred

array([0, 1, 1, 2, 0, 0, 2, 0, 0, 2, 2, 2, 0, 1, 0, 0, 0, 1, 0, 1, 2, 1,
       2, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 2, 2, 1, 1, 2])

In [48]:
y_test

31     0
91     1
76     1
115    2
40     0
19     0
116    2
46     0
2      0
135    2
139    2
101    2
5      0
92     1
34     0
33     0
10     0
90     1
49     0
73     1
129    2
53     1
149    2
43     0
61     1
22     0
85     1
81     1
71     1
82     1
15     0
138    2
60     1
128    2
142    2
50     1
106    2
109    2
Name: Target, dtype: int32

In [40]:
accuracy_score(y_test,y_pred)

0.9473684210526315

In [41]:
confusion_matrix(y_test,y_pred)

array([[13,  0,  0],
       [ 0, 13,  0],
       [ 0,  2, 10]], dtype=int64)

In [42]:
multilabel_confusion_matrix(y_test,y_pred)

array([[[25,  0],
        [ 0, 13]],

       [[23,  2],
        [ 0, 13]],

       [[26,  0],
        [ 2, 10]]], dtype=int64)

In [43]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.87      1.00      0.93        13
           2       1.00      0.83      0.91        12

    accuracy                           0.95        38
   macro avg       0.96      0.94      0.95        38
weighted avg       0.95      0.95      0.95        38



In [55]:
def model_eval(model,x,y):
    
    y_pred = model.predict(x)
    
    con_mat = confusion_matrix(y,y_pred)
    print(f'Confusion Matrix = \n{con_mat}')
    
    acc = accuracy_score(y,y_pred)
    print(f'Accuracy Score = {acc}')
    
    cl = classification_report(y,y_pred)
    print(f'Classification Report = \n{cl}')
    
    m_cl = multilabel_confusion_matrix(y,y_pred)
    print(f'Multiple Classification Matrix = \n{m_cl}')
    
    return 'Success'

model_eval(model,x_train,y_train)

Confusion Matrix = 
[[37  0  0]
 [ 0 35  2]
 [ 0  2 36]]
Accuracy Score = 0.9642857142857143
Classification Report = 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        37
           1       0.95      0.95      0.95        37
           2       0.95      0.95      0.95        38

    accuracy                           0.96       112
   macro avg       0.96      0.96      0.96       112
weighted avg       0.96      0.96      0.96       112

Multiple Classification Matrix = 
[[[75  0]
  [ 0 37]]

 [[73  2]
  [ 2 35]]

 [[72  2]
  [ 2 36]]]


'Success'

# user test Function

In [44]:
import pickle

In [45]:
with open('Logistic_Model.pkl','wb')as file:
    pickle.dump(model,file)

In [46]:
x_test.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
31                5.4               3.4                1.5               0.4
91                6.1               3.0                4.6               1.4
76                6.8               2.8                4.8               1.4

In [47]:
sl = 5.4
sw = 3.4
pl = 1.5
pw = 0.4

data = [sl,sw,pl,pw]
result = model.predict([data])
result

C:\Users\lenova\.conda\envs\homl3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [48]:
species = {0:'setosa',1:'versicolor',2:'virginica'}

In [62]:
result[0]

0

In [49]:
sl = 5.4
sw = 3.4
pl = 1.5
pw = 0.4

data = [sl,sw,pl,pw]
result = model.predict([data])
print(f'Predicted Species Of Iris = {species.get(result[0])}')

Predicted Species Of Iris = setosa


C:\Users\lenova\.conda\envs\homl3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [50]:
sl = float(input('Sepal Lenth in cm'))
sw = float(input('Sepal Width in cm'))
pl = float(input('Petal Lentgh in cm'))
pw = float(input('Petal Width in cm '))
data = [sl,sw,pl,pw]
result = model.predict([data])
print(f'Predicted Species Of Iris = {species.get(result[0])}')

Sepal Lenth in cm3.
Sepal Width in cm5.52
Petal Lentgh in cm2.5
Petal Width in cm 4.
Predicted Species Of Iris = setosa


C:\Users\lenova\.conda\envs\homl3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [51]:
import json 

with open('Specis.json','w')as file:
    json.dump(species,file)